
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Mar 15 12:27:37 EDT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A5Sym {
  /* terminals */
  public static final int _____________________ = 22;
  public static final int ____ = 5;
  public static final int ________ = 9;
  public static final int __________ = 11;
  public static final int _________________________ = 26;
  public static final int __________________ = 19;
  public static final int _____________ = 14;
  public static final int ___________________ = 20;
  public static final int ______ = 7;
  public static final int _________ = 10;
  public static final int __ = 3;
  public static final int ______________ = 15;
  public static final int _________________ = 18;
  public static final int _______________________ = 24;
  public static final int ______________________ = 23;
  public static final int EOF = 0;
  public static final int _______ = 8;
  public static final int _____ = 6;
  public static final int error = 1;
  public static final int ________________________ = 25;
  public static final int ____________ = 13;
  public static final int ___ = 4;
  public static final int _______________ = 16;
  public static final int ____________________ = 21;
  public static final int ________________ = 17;
  public static final int ___________ = 12;
  public static final int _ = 2;
}

